/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/back/app': RouteRecordInfo<'/back/app', '/back/app', Record<never, never>, Record<never, never>>,
    '/ConfigForm/': RouteRecordInfo<'/ConfigForm/', '/ConfigForm', Record<never, never>, Record<never, never>>,
    '/ConfigForm/ConfigForm': RouteRecordInfo<'/ConfigForm/ConfigForm', '/ConfigForm/ConfigForm', Record<never, never>, Record<never, never>>,
    '/form-demo/': RouteRecordInfo<'/form-demo/', '/form-demo', Record<never, never>, Record<never, never>>,
    '/form-demo/formDemo': RouteRecordInfo<'/form-demo/formDemo', '/form-demo/formDemo', Record<never, never>, Record<never, never>>,
    '/tree/': RouteRecordInfo<'/tree/', '/tree', Record<never, never>, Record<never, never>>,
    '/tree/FileIcon': RouteRecordInfo<'/tree/FileIcon', '/tree/FileIcon', Record<never, never>, Record<never, never>>,
    '/tree/fileSvg': RouteRecordInfo<'/tree/fileSvg', '/tree/fileSvg', Record<never, never>, Record<never, never>>,
    '/tree/p2': RouteRecordInfo<'/tree/p2', '/tree/p2', Record<never, never>, Record<never, never>>,
  }
}
